require('core/options')
require('core/autocmds')
require('core/keymaps')

require('core/lazy')
require('plugins/onedark')
-- require('plugins/tokyonight')
require('plugins/treesitter')
require('plugins/telescope')
require('plugins/harpoon')
require('plugins/gitsign')
require('plugins/comment')
require('plugins/surround')
require('plugins/worktree')
require('plugins/leap')
require('plugins/paperplanes')

require('lsp')
